apiVersion: v1
metadata:
  name: 'treasury-cluster'
baseDomain: BASE_DOMAIN
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  replicas: 1
  platform:
    aws:
      rootVolume:
        iops: 4000
        size: 100
        type: io1
      type: m5.xlarge
compute:
- hyperthreading: Enabled
  architecture: amd64
  name: 'worker'
  replicas: 0
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
networking:
  networkType: OVNKubernetes
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-east-1
pullSecret: "" # skip, hive will inject based on it's secrets
sshKey: |-
    ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDbSdFQaqi31q/Jypc37Im8zMTMzEytstwkK47mItNVxWdzAAGLeojOHHk2kJCkl/LoNS4PuJoTDuKmnf3+7Czx8hWRlIbwuRnHq6zdGhqQ4IZEtEH0kuWpY2V3aGF4+wVxw0ot7vfj0yvGpnTe2FycyGqPgDHu3v6JPk3/ctHeXw== noname