kind: AzureSqlServer
apiVersion: azure.microsoft.com/v1beta1
metadata:
  name: sqlserver-fsi
  namespace: hub-ns
spec:
  location: eastus
  resourceGroup: openenv-7z67p
---
kind: AzureSqlDatabase
apiVersion: azure.microsoft.com/v1beta1
metadata:
  name: fsi
  namespace: hub-ns
spec:
  edition: 1
  location: eastus
  resourceGroup: openenv-7z67p
  server: sqlserver-fsi
  sku:
    name: Basic
    tier: Basic
---
kind: AzureSqlFirewallRule
apiVersion: azure.microsoft.com/v1beta1
metadata:
  name: sqlf-fsi
  namespace: hub-ns
spec:
  endIpAddress: 0.0.0.0
  resourceGroup: openenv-7z67p
  server: sqlserver-fsi
  startIpAddress: 0.0.0.0